# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

ds_think_chat_model:
  api_key: "64b48697-0df7-44d0-b8fe-5ab19e789865"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "deepseek-v3-1-terminus"

ds_quick_chat_model:
  api_key: "64b48697-0df7-44d0-b8fe-5ab19e789865"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "deepseek-v3-1-terminus"

doubao_embedding_model:
  api_key: "64b48697-0df7-44d0-b8fe-5ab19e789865"
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  model: "doubao-embedding-vision-250615"
  dimensions: 2048

file_dir: "/home/lihaoqian/myproject/go_agent/docs/"
cls_mcp_url: "https://mcp-api.tencent-cloud.com/sse/77977c99c3e6593c"

redis:
  addr: "192.168.149.128:30379"
  db: 0
  dialTimeout: 2

# MySQL数据库配置
mysql:
  dsn: "root:123456@tcp(192.168.149.128:30306)/orm_test?charset=utf8mb4&parseTime=True&loc=Local&timeout=3s&readTimeout=5s&writeTimeout=5s"
  max_open_conns: 50
  max_idle_conns: 10
  conn_max_lifetime: "30m"
  conn_max_idle_time: "5m"
  ping_timeout: "3s"
  prepare_stmt: true
  log_level: "warn"
  slow_threshold: "500ms"

