apiVersion: v1
kind: ConfigMap
metadata:
  name: milvus-config
  namespace: infra
data:
  milvus.yaml: |
    etcd:
      endpoints:
        - etcd:2379
    minio:
      address: minio:9000
      accessKeyID: minioadmin
      secretAccessKey: minioadmin12345678
      useSSL: false
      bucketName: milvus-bucket
    common:
      chanNamePrefix:
        cluster: by-dev
        rootCoordTimeTick: rootcoord-timetick
        rootCoordStatistics: rootcoord-statistics
        rootCoordDml: rootcoord-dml
        rootCoordDelta: rootcoord-delta
        search: search
        searchResult: searchResult
        queryTimeTick: queryTimeTick
        queryNodeStats: query-node-stats
        dataCoordStatistic: datacoord-statistics-channel
        dataCoordTimeTick: datacoord-timetick-channel
        dataCoordSegmentInfo: segment-info-channel
