apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus
  namespace: infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: milvus
  template:
    metadata:
      labels:
        app: milvus
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9091"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: milvus
          image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/milvusdb/milvus:v2.6.6
          command: ["milvus", "run", "standalone"]
          env:
            - name: ETCD_ENDPOINTS
              value: "etcd:2379"
            - name: MINIO_ADDRESS
              value: "minio:9000"
          ports:
            - containerPort: 19530
              name: grpc
            - containerPort: 9091
              name: metrics
          volumeMounts:
            - name: data
              mountPath: /var/lib/milvus
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: 2000m
              memory: 4Gi
          securityContext:
            seccompProfile:
              type: Unconfined
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: milvus-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-data
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: milvus
  namespace: infra
spec:
  type: NodePort
  ports:
    - port: 19530
      targetPort: 19530
      nodePort: 31953
      name: grpc
    - port: 9091
      targetPort: 9091
      nodePort: 30091
      name: metrics
  selector:
    app: milvus
